<?php

/**
 * @file
 * Contains headhunter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function headhunter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the headhunter module.
    case 'help.page.headhunter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
